name: Build Go Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build and Test Services
        run: |
          echo "Building greeter..."
          cd greeter
          go mod tidy
          go build -v ./...

          echo "Building time-service..."
          cd ../time-service
          go mod tidy
          go build -v ./...